%=========== Global Variables for Virtual Lab GUI's

%=========== Pretty colors

clear TXTACTCL TXTDIMCL WINDOWCL TITLEFOR TITLEBAK OFFWHITE BLUEGREEN PURPLE GREEN;
clear BLACK WHITE RED BLUE YELLOW CYAN LIGHTGREY BLUEGREEN TEDITFOR TEDITBAK

clear MARGIN BOX1_H BOX2_H BOX1_W BOX2_W BOX3_W TEXT_H